project:
  type: website
  output-dir: docs
  post-render:
    - "touch docs/.nojekyll"

website:
  title: "Anindya Saha"
  site-url: https://anindya-saha.github.io
  sidebar:
    style: floating
    search: true
    contents:
      - text: "Blog"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "---"
      - text: "Categories"
        href: index.qmd#category
      - text: "---"
      - text: "GitHub"
        href: https://github.com/anindya-saha
        target: _blank
  page-footer:
    center: "Made with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
